{"name": "Проверка ошибки если логин уже существует", "status": "passed", "start": 1714454864106, "stop": 1714454865934, "uuid": "d9d86657-4d0c-4670-993f-a42530f83b3f", "historyId": "263e87dcbb1e03edeb1c23f103b6dc1a", "testCaseId": "263e87dcbb1e03edeb1c23f103b6dc1a", "fullName": "tests.test_creating_courier.TestCreatingCourier#test_error_is_login_that_already_exists", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_creating_courier"}, {"name": "subSuite", "value": "TestCreatingCourier"}, {"name": "host", "value": "GPRS"}, {"name": "thread", "value": "9812-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_creating_courier"}]}